spring:
  liquibase:
    change-log: classpath:/db/db-changelog.xml
  datasource:
    url: jdbc:postgresql://localhost:15432/hw_db
    username: user
    password: password
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  cache:
    type: redis
    cache-names: redis-cache
    redis:
      time-to-live: 30000
      use-key-prefix: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/sender
      database: sender
    redis:
      host: localhost
      port: 6379
      password: password


minio:
  url: http://localhost:9000
  port: 9000
  accessKey: user
  secretKey: password
  secure: false
  bucket: minio-storage
  image-size: 10485760

server:
  address: localhost
  port: 8080

logging:
  level:
    "liquibase": info