version: '3.1'
services:
  postgres:
    container_name: hw_db
    image: postgres
    environment:
      POSTGRES_DB: hw_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432